# Generated by Django 3.2.6 on 2021-08-18 15:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('blog_title', models.CharField(max_length=500, unique=True)),
                ('blog_slug', models.SlugField(allow_unicode=True, unique=True)),
                ('blog_content', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog_videos')),
                ('file', models.FileField(blank=True, null=True, upload_to='blog_files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'blog_title')},
            },
        ),
    ]
